services:
  country_csv_service:
    build: ./countries-microservice
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./countries-microservice/data/:/app/data
    ports:
      - 8000:8000
  authors_microservice:
    build: ./authors-microservice
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8001
    volumes:
      - ./countries-microservice/data/:/app/data
    ports:
      - 8001:8001
  nginx:
    image: nginx:latest
    ports:
      - 8080:8080
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - country_csv_service
      - authors_microservice
    
  
